// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnDd_ytyb_X1NVkJMM_84fn3fF56DhhIM',
    appId: '1:472029739757:web:cd79f1f5b90c4d6cb42ae4',
    messagingSenderId: '472029739757',
    projectId: 'medi-kit-d0b9d',
    authDomain: 'medi-kit-d0b9d.firebaseapp.com',
    storageBucket: 'medi-kit-d0b9d.firebasestorage.app',
    measurementId: 'G-R415SJ1X16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWmE39ROXziAJg08fXJ8KurZlfIPk3PEY',
    appId: '1:472029739757:android:118e2443ffa26625b42ae4',
    messagingSenderId: '472029739757',
    projectId: 'medi-kit-d0b9d',
    storageBucket: 'medi-kit-d0b9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEGq0qGUa4afeI1nC3WShuvoAHhDb1O9Q',
    appId: '1:472029739757:ios:02be258d6c42b244b42ae4',
    messagingSenderId: '472029739757',
    projectId: 'medi-kit-d0b9d',
    storageBucket: 'medi-kit-d0b9d.firebasestorage.app',
    iosClientId: '472029739757-cgnenfh3gc1tqkd8hr2p9jru7g0fmemk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEGq0qGUa4afeI1nC3WShuvoAHhDb1O9Q',
    appId: '1:472029739757:ios:02be258d6c42b244b42ae4',
    messagingSenderId: '472029739757',
    projectId: 'medi-kit-d0b9d',
    storageBucket: 'medi-kit-d0b9d.firebasestorage.app',
    iosClientId: '472029739757-cgnenfh3gc1tqkd8hr2p9jru7g0fmemk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediKit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnDd_ytyb_X1NVkJMM_84fn3fF56DhhIM',
    appId: '1:472029739757:web:bb252db140f883d0b42ae4',
    messagingSenderId: '472029739757',
    projectId: 'medi-kit-d0b9d',
    authDomain: 'medi-kit-d0b9d.firebaseapp.com',
    storageBucket: 'medi-kit-d0b9d.firebasestorage.app',
    measurementId: 'G-QSJB8Z1XGK',
  );
}
